name: flutter_test_various
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  go_router:
  google_sign_in:
  google_fonts:
  flutter_riverpod:
  flutter_hooks:
  hooks_riverpod:
  firebase_auth:
  sqflite: any
  path_provider: any
  riverpod_annotation: ^2.1.1
  firebase_core: ^2.15.0
  firebase_storage:
  cloud_firestore:
  image_picker:
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - images/no_image.png
    - images/inventory_top.png
    - images/account_pass.png
    - images/list_image1.png
    - images/list_image2.png
    - images/list_image3.png
    - images/list_image4.png
    - images/list_image5.png
    - images/Profiling_Isometric.png
    - images/Logistics_Isometric.png
    - images/Data Arranging_Isometric.png
