// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6MEgWi9I3DGY57TqNZ_7g_6gjGZgFt3c',
    appId: '1:599202083156:web:e23cc4281000e8fe2458c1',
    messagingSenderId: '599202083156',
    projectId: 'inventory-system-6bc22',
    authDomain: 'inventory-system-6bc22.firebaseapp.com',
    storageBucket: 'inventory-system-6bc22.appspot.com',
    measurementId: 'G-3P3JMQ4JZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChhwsX5rq0HkSJQtfbMHm1QoagQbTyNo',
    appId: '1:599202083156:android:e525fe2c30a32cb22458c1',
    messagingSenderId: '599202083156',
    projectId: 'inventory-system-6bc22',
    storageBucket: 'inventory-system-6bc22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLONX4Nrk3KT2eB7FJR_KXNHS1NQHRyLQ',
    appId: '1:599202083156:ios:3975dbcf6f5a1d362458c1',
    messagingSenderId: '599202083156',
    projectId: 'inventory-system-6bc22',
    storageBucket: 'inventory-system-6bc22.appspot.com',
    iosClientId: '599202083156-6lkqpmunng9j93qc69ue2jundcibfib7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestVarious',
  );
}
